export const ON_LOGIN = 'ON_LOGIN';
export const GET_LIST_ROUND = 'GET_LIST_ROUND';
export const GET_DETAIL_COMPETITION = 'GET_DETAIL_COMPETITION';
export const CONFIRM_ROUND_TEST = 'CONFIRM_ROUND_TEST';
